// Mapeamentos dos times da Copa 2026 (nomes exatos da football-data.org)

// Tradução Inglês -> Português
const teamNamesMap: { [key: string]: string } = {
  'Algeria': 'Argélia',
  'Argentina': 'Argentina',
  'Australia': 'Austrália',
  'Austria': 'Áustria',
  'Belgium': 'Bélgica',
  'Bosnia-Herzegovina': 'Bósnia',
  'Bosnia and Herzegovina': 'Bósnia',
  'Brazil': 'Brasil',
  'Canada': 'Canadá',
  'Cape Verde Islands': 'Cabo Verde',
  'Cape Verde': 'Cabo Verde',
  'Colombia': 'Colômbia',
  'Congo DR': 'RD Congo',
  'Democratic Republic of the Congo': 'RD Congo',
  'Croatia': 'Croácia',
  'Curaçao': 'Curaçao',
  'Czechia': 'República Tcheca',
  'Czech Republic': 'República Tcheca',
  'Ecuador': 'Equador',
  'Egypt': 'Egito',
  'England': 'Inglaterra',
  'France': 'França',
  'Germany': 'Alemanha',
  'Ghana': 'Gana',
  'Haiti': 'Haiti',
  'Iran': 'Irã',
  'Iraq': 'Iraque',
  'Ivory Coast': 'Costa do Marfim',
  'Japan': 'Japão',
  'Jordan': 'Jordânia',
  'Mexico': 'México',
  'Morocco': 'Marrocos',
  'Netherlands': 'Holanda',
  'New Zealand': 'Nova Zelândia',
  'Norway': 'Noruega',
  'Panama': 'Panamá',
  'Paraguay': 'Paraguai',
  'Portugal': 'Portugal',
  'Qatar': 'Catar',
  'Saudi Arabia': 'Arábia Saudita',
  'Scotland': 'Escócia',
  'Senegal': 'Senegal',
  'South Africa': 'África do Sul',
  'South Korea': 'Coreia do Sul',
  'Spain': 'Espanha',
  'Sweden': 'Suécia',
  'Switzerland': 'Suíça',
  'Tunisia': 'Tunísia',
  'Turkey': 'Turquia',
  'United States': 'EUA',
  'Uruguay': 'Uruguai',
  'Uzbekistan': 'Uzbequistão',
};

// Código de exibição no padrão do protótipo (ex: South Africa -> AFRI)
const codeMap: { [key: string]: string } = {
  'South Africa': 'AFRI',
  'Czechia': 'TCH',
  'United States': 'EUA',
  'Germany': 'ALE',
  'Saudi Arabia': 'ARA',
  'England': 'ING',
  'Curaçao': 'CUR',
  'Cape Verde Islands': 'CAB',
  'Netherlands': 'HOL',
  'Jordan': 'JOR',
  'Uzbekistan': 'UZB',
  'Tunisia': 'TUN',
  'Morocco': 'MAR',
  'Senegal': 'SEN',
  'Algeria': 'ALG',
  'Egypt': 'EGI',
  'Ghana': 'GAN',
  'Norway': 'NOR',
  'Sweden': 'SUE',
  'Switzerland': 'SUI',
  'Croatia': 'CRO',
  'Belgium': 'BEL',
  'Austria': 'AUT',
  'Bosnia-Herzegovina': 'BOS',
  'Iraq': 'IRA',
  'Iran': 'IRÃ',
  'Japan': 'JAP',
  'South Korea': 'KOR',
  'Australia': 'AUS',
  'New Zealand': 'NZL',
  'Haiti': 'HAI',
  'Panama': 'PAN',
  'Ecuador': 'EQU',
  'Uruguay': 'URU',
  'Colombia': 'COL',
  'Mexico': 'MEX',
  'Brazil': 'BRA',
  'Argentina': 'ARG',
  'France': 'FRA',
  'Spain': 'ESP',
  'Portugal': 'POR',
  'Canada': 'CAN',
  'Paraguay': 'PAR',
  'Qatar': 'CAT',
  'Scotland': 'ESC',
  'Turkey': 'TUR',
  'Ivory Coast': 'CIV',
  'Congo DR': 'CON',
};

// Código de país para a bandeira no flagcdn.com
const iso2Map: { [key: string]: string } = {
  'Algeria': 'dz',
  'Argentina': 'ar',
  'Australia': 'au',
  'Austria': 'at',
  'Belgium': 'be',
  'Bosnia-Herzegovina': 'ba',
  'Bosnia and Herzegovina': 'ba',
  'Brazil': 'br',
  'Canada': 'ca',
  'Cape Verde Islands': 'cv',
  'Cape Verde': 'cv',
  'Colombia': 'co',
  'Congo DR': 'cd',
  'Croatia': 'hr',
  'Curaçao': 'cw',
  'Czechia': 'cz',
  'Czech Republic': 'cz',
  'Ecuador': 'ec',
  'Egypt': 'eg',
  'England': 'gb-eng',
  'France': 'fr',
  'Germany': 'de',
  'Ghana': 'gh',
  'Haiti': 'ht',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Ivory Coast': 'ci',
  'Japan': 'jp',
  'Jordan': 'jo',
  'Mexico': 'mx',
  'Morocco': 'ma',
  'Netherlands': 'nl',
  'New Zealand': 'nz',
  'Norway': 'no',
  'Panama': 'pa',
  'Paraguay': 'py',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Saudi Arabia': 'sa',
  'Scotland': 'gb-sct',
  'Senegal': 'sn',
  'South Africa': 'za',
  'South Korea': 'kr',
  'Spain': 'es',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Tunisia': 'tn',
  'Turkey': 'tr',
  'United States': 'us',
  'Uruguay': 'uy',
  'Uzbekistan': 'uz',
};

// Nome das fases do mata-mata
const stageNamesPt: { [key: string]: string } = {
  GROUP_STAGE: 'Fase de Grupos',
  LAST_32: '16 avos de Final',
  LAST_16: 'Oitavas de Final',
  QUARTER_FINALS: 'Quartas de Final',
  SEMI_FINALS: 'Semifinal',
  THIRD_PLACE: 'Disputa do 3º Lugar',
  FINAL: 'Final',
};

export const translateTeam = (name: string): string => teamNamesMap[name] || name;

export const mapFifaCode = (teamNameEn: string, originalCode: string): string =>
  codeMap[teamNameEn] || originalCode || (teamNameEn || '').slice(0, 3).toUpperCase();

// Retorna o código iso2 para o flagcdn ou, se o país não estiver mapeado,
// a URL da bandeira fornecida pela própria API (crest)
export const flagOf = (teamNameEn: string, crestUrl: string): string =>
  iso2Map[teamNameEn] || crestUrl || 'un';

// "GROUP_A" -> "Grupo A"; mata-mata usa o nome da fase
export const groupLabel = (stage: string | null, groupName: string | null): string => {
  if (groupName) {
    const letter = groupName.replace('GROUP_', '').replace('Group ', '');
    return `Grupo ${letter}`;
  }
  return stageNamesPt[stage || ''] || 'Copa 2026';
};

// Monta a URL da imagem da bandeira (aceita iso2 do flagcdn ou URL completa do crest)
export const flagSrc = (flag: string, size: number): string =>
  flag.startsWith('http') ? flag : `https://flagcdn.com/w${size}/${flag}.png`;

// Retorna as cores principais da bandeira de cada seleção (Copa 2026)
export const getTeamColors = (teamNameEn: string): string[] => {
  const normalized = (teamNameEn || '').trim();
  const colorsMap: { [key: string]: string[] } = {
    'Algeria': ['#006233', '#ffffff', '#d21034'],
    'Argentina': ['#75aadb', '#ffffff', '#75aadb'],
    'Australia': ['#00008b', '#ffcd00', '#00843d'],
    'Austria': ['#ed2939', '#ffffff', '#ed2939'],
    'Belgium': ['#000000', '#ffd100', '#ff0f21'],
    'Bosnia-Herzegovina': ['#002395', '#fecb00', '#002395'],
    'Bosnia and Herzegovina': ['#002395', '#fecb00', '#002395'],
    'Brazil': ['#009739', '#fedf00', '#002776'],
    'Canada': ['#ff0000', '#ffffff', '#ff0000'],
    'Cape Verde Islands': ['#003893', '#ffd100', '#d21034'],
    'Cape Verde': ['#003893', '#ffd100', '#d21034'],
    'Colombia': ['#fcd116', '#003893', '#ce1126'],
    'Congo DR': ['#007FFF', '#FDD017', '#D21034'],
    'Democratic Republic of the Congo': ['#007FFF', '#FDD017', '#D21034'],
    'Croatia': ['#ff0000', '#ffffff', '#171796'],
    'Curaçao': ['#002b7f', '#f9e316', '#002b7f'],
    'Czechia': ['#11457e', '#ffffff', '#d7141a'],
    'Czech Republic': ['#11457e', '#ffffff', '#d7141a'],
    'Ecuador': ['#ffdd00', '#0033a0', '#d51a2b'],
    'Egypt': ['#c09307', '#ffffff', '#e4312b'],
    'England': ['#ffffff', '#ce1124', '#ffffff'],
    'France': ['#002654', '#ffffff', '#ed2939'],
    'Germany': ['#000000', '#dd0000', '#ffce00'],
    'Ghana': ['#e41c2c', '#fed100', '#008751'],
    'Haiti': ['#00209f', '#d21034', '#00209f'],
    'Iran': ['#239e46', '#ffffff', '#da0000'],
    'Iraq': ['#ff0000', '#ffffff', '#000000'],
    'Ivory Coast': ['#f77f00', '#ffffff', '#009e60'],
    'Japan': ['#ffffff', '#bc002d', '#ffffff'],
    'Jordan': ['#000000', '#ffffff', '#007a3d'],
    'Mexico': ['#006847', '#ffffff', '#c8102e'],
    'Morocco': ['#c1272d', '#006233', '#c1272d'],
    'Netherlands': ['#21468b', '#ffffff', '#ae1c28'],
    'New Zealand': ['#000000', '#ffffff', '#000000'],
    'Norway': ['#ef2b2d', '#ffffff', '#00205b'],
    'Panama': ['#da121a', '#ffffff', '#072357'],
    'Paraguay': ['#d52b1e', '#ffffff', '#0038a8'],
    'Portugal': ['#006600', '#ff0000', '#ffff00'],
    'Qatar': ['#8a1538', '#ffffff', '#8a1538'],
    'Saudi Arabia': ['#006c35', '#ffffff', '#006c35'],
    'Scotland': ['#005eb8', '#ffffff', '#005eb8'],
    'Senegal': ['#e41d2d', '#fec223', '#118b44'],
    'South Africa': ['#007a4d', '#ffb81c', '#002395'],
    'South Korea': ['#ffffff', '#cd2e3a', '#0a59f7'],
    'Spain': ['#c1272d', '#fecb00', '#c1272d'],
    'Sweden': ['#006aa7', '#fecc00', '#006aa7'],
    'Switzerland': ['#da291c', '#ffffff', '#da291c'],
    'Tunisia': ['#e70013', '#ffffff', '#e70013'],
    'Turkey': ['#e30a17', '#ffffff', '#e30a17'],
    'United States': ['#3c3b6e', '#ffffff', '#b22234'],
    'Uruguay': ['#0081c8', '#ffffff', '#fcd116'],
    'Uzbekistan': ['#00aeef', '#ffffff', '#1c355e'],
  };
  return colorsMap[normalized] || ['#8b8075', '#a8a29e', '#d6d3d1'];
};
